### ISSUE TITLE
iOS notification opens safari browser

### ISSUE THREAD

**Issue by aamir-ans** [CleverTap/clevertap-react-native#164] opened 2021-05-26 16:14 UTC
@Aditi3 When I click on the notification it opens in browser instead of app. The issue with push notification has a deep link with an http/https URL. I'm using latest clevertap SDK. Kindly let me know if any changes require on configuration side.

**Comment by Aditi3** [comment] 2021-05-26 16:27
Hi @aamir-ans ,

Could you refer to the comment [here](https://github.com/CleverTap/clevertap-react-native/issues/149#issuecomment-826343713) and it seems to be a duplicate of #149 & #139.

**Comment by aamir-ans** [comment] 2021-05-27 13:09
@Aditi3 Thanks that works, now the problem is I'm not getting any event when app is completely closed, notification click just opens the app. It's working fine for foreground and background.

**Comment by aamir-ans** [comment] 2021-05-27 17:08
@Aditi3 I'm not getting any data or event when click on notification while using Custom key-value pairs in notification. This happens when app is completely closed and notification clicked.
Kindly help me on this.

**Comment by Aditi3** [comment] 2021-05-28 10:23
@aamir-ans looking into this today. We'll keep you posted.

**Comment by aamir-ans** [comment] 2021-05-31 13:29
@Aditi3 Any update on this issue ?

**Comment by Aditi3** [comment] 2021-05-31 13:41
For push notifications, launched from killed state you need to implement following piece of code, the reason being when the app starts from the killed state, React Native takes some time to initialize the JS Core. Due to this the push notification click callback fired by OS is missed in RN. The callback is fired earlier than RN listeners get set up.

In your `AppDelegate.m` file, under `didFinishLaunchingWithOptions` method pass `launchOptions` with initial properties as below

```
RCTRootView *rootView [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ReactNativeExampleiOS"
                                            initialProperties:launchOptions];
```
Now in the App.js file under App class, please make changes as below

```
class App extends React.Component {

  constructor(props){
      super(props);
      console.log('initial props:', props);
      if(props.UIApplicationLaunchOptionsRemoteNotificationKey){
    	 Alert.alert(JSON.stringify(props.UIApplicationLaunchOptionsRemoteNotificationKey)); // here you can get the payload 
      }
   }
}
```

**Comment by Aditi3** [comment] 2021-06-07 10:32
I hope it worked for you. I'm going to close this thread feel free to reopen it if you need further help.

**Closed by Aditi3** 2021-06-07 10:32 UTC
Labels: platform: iOS

**Comment by jfbn** [comment] 2021-06-16 08:53
Hi @Aditi3,
We have been using CleverTap for a few weeks now, and I have just yesterday identified that this problem is occurring for us as well.
From reading your replies in this thread and in the other similar threads, I still do not understand how to solve the issue.
In one of the other threads you wrote this:
>If the push notification has a deep link with an http/https URL, it invokes the app. Later it will be redirected to the browser. This is default behaviour at the OS level.
I don't understand that this should be the default behaviour at the OS level. If it is, how can I circumvent it?

The deeplinks work but not when triggered from a Push Notification. 

I can open a support ticket via the website if that is preferable.
