### ISSUE TITLE
iOS deep link issue

### ISSUE THREAD

**Issue by aamir-ans** [CleverTap/clevertap-react-native#126] opened 2020-12-21 16:10 UTC
@Aditi3 When click on notification in iOS some deep link URL opens safari browser ? any specific use case I'm missing ? I have defined URL schemes as well but still redirecting to safari browser

**Comment by Aditi3** [comment] 2020-12-23 02:24
@aamir-ans It seems to be an unexpected behaviour if you're using URL schemes/ custom deep links/ Universal links correctly.

I am not sure what have you missed here, hence I would suggest raising a support ticket from the dashboard which includes details of your campaign link so that we can look into this further and help you in resolving the issue at the earliest.

Thank you

**Comment by Aditi3** [comment] 2021-01-12 02:56
Closing this as it is being moved to support.

**Closed by Aditi3** 2021-01-12 02:56 UTC
Labels: moved to support
