### ISSUE TITLE
PushNotification integration

### ISSUE THREAD

**Issue by gaelperon** [CleverTap/clevertap-react-native#105] opened 2020-08-17 15:56 UTC
Hello Clevertap,

It would be really nice to have a clear guide to setup push notifications with the React Native SDK.

For now, you have to cherry-pick information in ios guide and android guide which is very painful and confusing

**Comment by Aditi3** [comment] 2020-08-18 06:13
Hi @gaelperon 

Thank you for your feedback and apologies for the inconvenience caused to you.

We will work on updating the integration and installation guide to give a clear understanding of all modules for both platform Android and iOS. You can expect the Developer guide to be updated soon and we will keep you posted.

Best, 
Aditi

**Comment by gaelperon** [comment] 2020-08-18 06:48
Well thanks.

In the ReactNative example you can see this call :

`CleverTap.setPushToken('abcdfcm', CleverTap.FCM);`

Is it for Android ? IOS ? both ?
And what should how should I get the token => 'abcdfcm' in the example

**Comment by gaelperon** [comment] 2020-08-18 10:02
When I try to test on the iOS simulator is get this error : `APNSBadDeviceToken`

The device seems to be registered in the Clevertap interface

<img width="489" alt="Capture d’écran 2020-08-18 à 12 01 02" src="https://user-images.githubusercontent.com/5892710/90500018-9b722500-e14a-11ea-93e5-d649f5827b1d.png">

<img width="1474" alt="Capture d’écran 2020-08-18 à 12 00 48" src="https://user-images.githubusercontent.com/5892710/90500033-a1680600-e14a-11ea-94ad-f58ce279d070.png">

Is it possible to test on the iOS simulator ?

**Comment by gaelperon** [comment] 2020-08-18 10:05
And on Android I get this error 

<img width="487" alt="Capture d’écran 2020-08-18 à 12 04 45" src="https://user-images.githubusercontent.com/5892710/90500378-13404f80-e14b-11ea-90ee-268f838482a9.png">
<img width="1485" alt="Capture d’écran 2020-08-18 à 12 04 24" src="https://user-images.githubusercontent.com/5892710/90500382-14717c80-e14b-11ea-90b3-1460af695ad7.png">

I suppose I'm initializing with the wrong token for both Android and iOS, but it's not clear how to get the tokens ?

**Comment by piyush-kukadiya** [comment] 2020-08-19 16:21
@gaelperon For Android you will need to setup push notifications natively please go through [this link](https://developer.clevertap.com/docs/android#section-push-notifications)

**Comment by gaelperon** [comment] 2020-08-19 16:26
Thanks, I managed to make it work on Android following this guide.

How do you get APNS token on iOS ?

**Comment by Aditi3** [comment] 2020-08-19 16:32
Hi @gaelperon 

For iOS, use the `registerForPush` API to register and fetch the APNS token:

Helping Link: https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L88

Our Demo Application Link describing APNS implementation: https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js#L66

**Comment by gaelperon** [comment] 2020-08-24 08:01
Thanks @Aditi3 

How do handle deep links in iOS notifications? 

It works OK on Android, but it keeps forwarding me to Safari browser in iOS.
Do you need to implement something in the AppDelegate ?

**Comment by Aditi3** [comment] 2020-08-24 12:16
@gaelperon I'd recommend implementing the URL Schemes/ Custom deep links/ Universal links to handle internal Deeplinks in iOS.

**Comment by gaelperon** [comment] 2020-08-24 15:23
I already handle deeplink via universal links in the app, but for now, when I click on the notification, it doesn't enter into the app, it directly opens Safari without calling Linking.openURL

**Comment by Aditi3** [comment] 2020-08-24 15:51
@gaelperon It seems to be an unexpected behaviour if you're using custom deep links/ Universal links correctly.

Not sure what you are missing, hence I would suggest raising a support ticket from the dashboard which includes details of your use case and campaign link so that we can look into this further and help you in resolving the issue at the earliest.

Thank you

**Comment by rawris** [comment] 2020-09-15 06:58
@gaelperon Can you share your code or can you guide me what you did for Android integration of clevertap? I have added everything in Androidmanifest.xml. What am I supposed to do now?

**Comment by piyush-kukadiya** [comment] 2020-11-05 09:46
@rawris Are you still facing the issue?

**Comment by gaelperon** [comment] 2020-11-05 09:48
@piyush-kukadiya The issue has been solved thanks to your support.

**Closed** 2020-11-20 05:08 UTC
Labels: documentation, enhancement, moved to support
