### ISSUE TITLE
Deeplinking not working on click on notification when app is closed

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [CleverTap/clevertap-react-native#141] opened 2021-03-18 17:19 UTC
When app is in background , i am able to receive notification and on click on notification , deeplinking  redirect to correct screen.

when app is in foreground , open   , then i am not receiving notification

when app is closed then on click on notification  , app is opening but not redirecting to correct screen . means it just opens app

**Comment by Aditi3** [comment] 2021-03-22 16:16
Please refer to the response here - https://github.com/CleverTap/clevertap-react-native/issues/125#issuecomment-742427995

Duplicate of #125

**Comment by Aditi3** [comment] 2021-03-24 02:45
Closing this thread.

**Closed by Aditi3** 2021-03-24 02:45 UTC
Labels: question
